### ISSUE TITLE
trigger in EEG channel bug

### ISSUE THREAD

**Issue by dmedine** [brain-products/LSL-BrainAmpSeries#4]
https://github.com/labstreaminglayer/App-BrainAmpSeries/issues/9

**Comment by dmedine** [comment]
I went over the code and it looks correct, but that doesn't necessarily mean anything. @jalevitt, can you please let me know that sampling rate you are using? I assume 5kHz. This code did change a lot when I implemented the downsampling feature, but I seem to remember the tests passing. It is possible that I didn't test it at 5kHz though. Unfortunately I currently don't have access to a device. I am waiting on a loan to get back from a lab that is locked down due to local Covid restrictions. It may be a month or more before I can actually test this properly and fix the bug. Until then I can provide you with a downsampler-less version of the app with the 'old' way of handling the triggers.

**Comment by jalevitt** [comment]
Correct, it was at 5kHz. Anything you can send would be appreciated. I’m
going to do some more testing tomorrow afternoon to make sure it’s not an
issue on my end, but I don’t think it is.


Thanks again!

**Comment by dmedine** [comment]
@jalevitt I don't think it is an issue on your end either. Rather, I think that it was a bug introduced when I added the downsampling feature. 

I have attempted to fix this bug, but it is impossible to know if it is correct without a device, so no promises I'm afraid. I re-instated the trigger handling from the previous version of the app so in theory this is once again correct (although from analyzing the code I cannot fathom why it wasn't correct in the first place). 

Here is a link to the app: https://drive.google.com/file/d/1UOPhOvIhRgBz6ZPIVa8mZjZu3__WUKtv/view?usp=sharing Please let me know if anything is broken. Unfortunately, until I have a device in my hands I can only guess and hope that there are no bugs. 

In this version of the app you now have the option to set the hardware filter as well. You probably know all this, but just to avoid even more confusion, for in-scanner recordings Brain Products recommend the following settings:
Sampling rate: 5kHz
DC Coupling: AC (note that in Recorder this is actually the 'Low Cutoff ' parameter---AC coupling corresponds to 10 seconds, DC to DC)
Resolution: 100nV (in Recorder the units are microvolt so the value is .1). This is the only available resolution in the case of BrainAmp MR, but BrainAmp MRplus can also run at 500nV. However, in the scanner the resolution should always be 100.

**Comment by jalevitt** [comment]
Just did some more testing with the code you sent, and this seems to have resolved the issue! I'm going to test everything tomorrow in the scanner tomorrow with a phantom, but it seems like everything is in order. One small question: Which setting for the hardware filter is correct for the scanner?
